- name: Install keyd packages
  ansible.builtin.apt:
    state: present
    name:
      - keyd
      - keyd-application-mapper

- name: Symlink keyd configuration
  ansible.builtin.file:
    src: "{{ keyd_config_src }}"
    dest: "{{ keyd_config_dest }}"
    state: link

- name: Enable keyd service
  ansible.builtin.systemd:
    name: keyd
    enabled: true
    daemon_reload: true

- name: Reload keyd
  ansible.builtin.command:
    cmd: keyd.rvaiya reload
