tools_enabled: true
tools_features:
  devtools: true
  media: true
  productivity: true
  virtualization: true

tools_packages:
  devtools:
    - shellcheck

  media: []
  productivity: []

  virtualization:
    - virt-manager
    - gnome-boxes
