- name: Check if role is enabled
  ansible.builtin.meta: end_role
  when: not tools_enabled | bool

- name: Dev tools
  ansible.builtin.include_tasks: devtools.yml
  when: tools_features.devtools | bool

- name: Media tools
  ansible.builtin.include_tasks: media.yml
  when: tools_features.media | bool

- name: Productivity tools
  ansible.builtin.include_tasks: productivity.yml
  when: tools_features.productivity | bool

- name: Virtualization tools
  ansible.builtin.include_tasks: virtualization.yml
  when: tools_features.virtualization | bool
