- name: Install virtualization packages
  ansible.builtin.apt:
    name: "{{ tools_packages.virtualization }}"
    state: present

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: libvirt
    append: true
