- name: Ensure user directories exist
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ base_directories }}"
  become: false
