- name: Disable unused services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ post_install_disable_services }}"

- name: Uninstall unused packages
  ansible.builtin.apt:
    name: "{{ post_install_remove_packages }}"
    state: absent

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true

- name: Reboot
  ansible.builtin.reboot:
  when:
    - post_install_reboot is defined
    - post_install_reboot | bool
